# Generated by Django 3.0.3 on 2020-02-28 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('docs', models.CharField(max_length=20, verbose_name='商品描述')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='shop.Category', verbose_name='所属分类')),
            ],
        ),
        migrations.CreateModel(
            name='GoodImgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='goodimg', verbose_name='商品图')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='shop.Good', verbose_name='商品')),
            ],
        ),
    ]
