# Generated by Django 3.0.3 on 2020-02-15 03:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20200215_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
            ],
            options={
                'verbose_name': '用户模型',
                'verbose_name_plural': '用户模型',
                'db_table': '用户类',
                'ordering': ['id'],
            },
            managers=[
                ('delete', django.db.models.manager.Manager()),
            ],
        ),
    ]
